apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: login-app
  name: login-app
spec:
  containers:
    - image: registry.gitlab.com/id/k8s-data/sample:v1
      name: login-app
  restartPolicy: Always
  imagePullSecrets:
    - name: app-secret